### ISSUE TITLE
Enable via story parameter

### ISSUE THREAD

**Issue by spicattutti** [chromaui/storybook-outline#16]
Hey folks,

is there a way to make a story initially show outlines? So that the viewer does not have to (know of and) press the button?

**Comment by winkerVSbecks** [comment]
This repo is deprecated. The outline addon was moved to the Storybook core repo: https://github.com/storybookjs/storybook/tree/next/code/addons/outline

**Comment by winkerVSbecks** [comment]
And no, it doesn't support params but it does support globals. For example: 

```
mystorybook.com/?path=/story/avatarlist--basic&globals=outline:!true
```

You can open a feature request on the main repo
